### ISSUE TITLE
PointCloud scale might be wrong

### ISSUE THREAD

**Issue by nisshan-x** [MagikEyeInc/SDK#2]
I launched mkeros on ros1, and called service to start publishing topic. Then I got sensormsgs::PointCloud2. I put my hand over the device, but it looks super huge!

Reproduce Procedure:

Terminal 1
```
roscore
```

Terminal 2
```
roslaunch mkeros mkeros1_cpp.launch
```

Terminal 3
```
rosservice call /mkeros1_startpublish_s1
```

terminal 4
```
rviz
```

<img width="1156" alt="スクリーンショット 2021-07-23 20 34 02" src="https://user-images.githubusercontent.com/67353276/126776736-8379ae47-1aeb-4f2d-bbea-e211e88f0ef7.png">
<img width="1153" alt="スクリーンショット 2021-07-23 20 34 16" src="https://user-images.githubusercontent.com/67353276/126776756-2a72f1a6-093f-4f01-9c66-7ed688200ca1.png">
<img width="1149" alt="スクリーンショット 2021-07-23 20 36 39" src="https://user-images.githubusercontent.com/67353276/126776763-995ed53b-b675-4ce2-b5c4-067eb34afed6.png">
<img width="1148" alt="スクリーンショット 2021-07-23 20 36 56" src="https://user-images.githubusercontent.com/67353276/126776781-abf34ac0-142f-4cb9-9c37-aec61ef81be8.png">

The default size of the cells in the grid is 1 meter.
[rviz/DisplayTypes/Grid](http://wiki.ros.org/rviz/DisplayTypes/Grid)

**Comment by nisshan-x** [comment]
I found in ros document : 
*We have chosen to standardize on SI units.*

https://www.ros.org/reps/rep-0103.html

**Comment by jan-heller** [comment]
Fixed by e4a3ac92a7ec5bf57978d15d43feb81b1f595653.

**Comment by nisshan-x** [comment]
I git-cloned the latest ros1 package (v.1.1.2), catkin_maked, and launched. But the size of pointcloud in rviz is still wrong.

Please take a look.
